language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -f Dockerfile.dev -t umaqgeek/react-test .

script:
    - docker run -e CI=true umaqgeek/react-test npm run test